### PR TITLE
Added web support

### PR DESCRIPTION
**Pull request by chetu-ko**
Hello @saibotma,

Here I have added the web support with reference of jitsi_meet flutter package. Please make sure that everything is fine while merging and feel free to ask anything or give feeedback related this pullrequest. Issue opened #11

Thannk you.

### CODE REVIEW

**Comment by thorito** [comment]
Hello @chetu-ko
First, I want to thank you for the work you have done.

I have the following problem:
In release mode, events appear hidden.

Do you know what it is?

Thank you so much

**Comment by chetu-ko** [comment]
Hi @thorito
Thanks for your reply.

Events appear hidden means, I didn't get it. The event needs to be shown in the logs or else events are not working.

**Comment by thorito** [comment]
> 

Sorry for my bad explanation :( 

When you click on the buttons to mute the microphone, for example, the listener does not detect correctly because the code is obfuscated.

https://user-images.githubusercontent.com/594395/222778111-44ae7484-5375-4881-8e67-ebedf9a8171b.mov

**Comment by chetu-ko** [comment]
@thorito I am trying to resolve it. It would be great if you could suggest to me or find a solution to resolve that. Please Let me know, I would love to accept your suggestion. :)

**Comment by thorito** [comment]
Sorry I do not know

**Pull request closed without merging**
